In [1]:
# Importing Libraries & # Importing selenium webdriver 
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd
import os
import datetime
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium import webdriver

In [2]:
# Activating the chrome browser
driver= webdriver.Chrome(r"C:\Users\shobh\Downloads\chromedriver_win32\chromedriver.exe")

In [3]:
url = "https://www.naukri.com/"
driver.get(url)
driver.implicitly_wait(20)

In [7]:
Recruiter = driver.find_element_by_xpath('//a[@href="https://www.naukri.com/recruiters"]')
Recruiter.click()
print (Recruiter.get_attribute('href'))
action = ActionChains(driver)
# clicks on located link element with CONTROL button in pressed state using actionChains class. This opens the link in new tab 
action.key_down(Keys.CONTROL).click(Recruiter).key_up(Keys.CONTROL).perform() 
driver.switch_to.window(driver.window_handles[1])
driver.find_element_by_xpath('//input[@class="sugInp"]').send_keys("Data Science")
driver.find_element_by_xpath('//button[@id="qsbFormBtn"]').click()
rows = driver.find_elements_by_xpath('//div[@id="tabP-1"]//div[@class="outerRecSec"]')
col_l = rows[0].find_element_by_xpath('div[@class="recSec fl fadeInUp"]')
col_r = rows[0].find_element_by_xpath('div[@class="recSec fr fadeInUp"]')
# Fetching required details
Name_l = col_l.find_elements_by_xpath("div/div/p/a")[0].text
Designation_l = col_r.find_elements_by_xpath("div/div/p/span")[0].text
Company_l = col_l.find_elements_by_xpath("div/div/p/a")[1].text
Skill_l = col_l.find_element_by_xpath('div/div[@class="hireSec highlightable"]').text
Loc_l =  col_r.find_elements_by_xpath("div/div/p/span")[1].text
#Creating empty list
name=[]
designation=[]
company=[]
skill=[]
loc=[]

for i in rows:
    try:
        name.append(i.find_element_by_xpath('div[@class="recSec fl fadeInUp"]').find_elements_by_xpath("div/div/p/a")[0].text)
    except:
        name.append('')
    try:
        designation.append(i.find_element_by_xpath('div[@class="recSec fl fadeInUp"]').find_elements_by_xpath("div/div/p/span")[0].text)
    except:
        designation.append('')
    try:
        company.append(i.find_element_by_xpath('div[@class="recSec fl fadeInUp"]').find_elements_by_xpath("div/div/p/a")[1].text)
    except:
        company.append('')
    try:
        skill.append(i.find_element_by_xpath('div[@class="recSec fl fadeInUp"]').find_element_by_xpath('div/div[@class="hireSec highlightable"]').text)
    except:
        skill.append('')
    try:
        loc.append(i.find_element_by_xpath('div[@class="recSec fl fadeInUp"]').find_elements_by_xpath("div/div/p/span")[1].text)
    except:
        loc.append('')

https://www.naukri.com/recruiters

In [8]:
# creating data frame
df = pd.DataFrame({'Name':name,'Designation':designation,'Company':company,'Skill':skill,'Location':loc})

In [9]:
df

,Name,Designation,Company,Skill,Location
0,Rajiv Raj,Director,CreditVidya,"Big Data, Data Management, Data Analytics, Ban...",Mumbai
1,Malvika Bhandari,Talent Acquisition Consultant,IMS Proschool Pvt. Ltd,Not Specified,Pune
2,Vineet P,Opportunity Communicator,Dell Technologies,"Inside Sales, Outside Sales, Enterprise Accoun...",Bengaluru / Bangalore
3,Tracy Raina,Senior HR Executive,Quatrro Global Services Pvt. Ltd.,Not Specified,Gurgaon
4,Deepti Nagle,Recruitment Executive,Nityo Infotech Services Pvt. Ltd.,Not Specified,Pune
5,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
6,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
7,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
10,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
11,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
12,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
13,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
14,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
15,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
16,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
17,Dr. S. Prasanna Devi,Professor and Head,SRM Institute of Science and Technology,"Computer Science, Machine Learning, Deep Learn...",Chennai
18,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",
19,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
20,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
21,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
22,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
23,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
24,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City